config/routes.rb
Rails.application.routes.draw do

  mount ActionCable.server => '/cable'

  resources :leaderboard, :only => [:index]

  get 'update_color', to: 'dashboard#update_color'
  get 'fav_colors', to: 'leaderboard#fav_colors'

  root 'dashboard#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/matrix.rb
class Matrix < ApplicationRecord

  #ASSOCIATIONS
  belongs_to :user, optional: true

  # VALIDATIONS
  validates_format_of :color, with: /#?([A-F0-9]{3}){1,2}/i, on: :update
  validates_presence_of :user_id, on: :update

  scope :top_users, -> { select('user_id, color, count(DISTINCT(color)) AS distinct_color_count,
                                 count(color) AS color_count').
                         where('user_id IS NOT NULL').
                         group(:user_id).
                         includes(:user).
                         order('distinct_color_count DESC, color_count DESC') }

  scope :by_fav_colors, -> { select("color, count(*) as count").
                             order('count DESC').
                             group(:color) }

  def update_color user_id, color
    update_attributes(user_id: user_id, color: color)
  end

  def display_title
    "#{user.name.camelcase}, #{updated_at.strftime('%d/%m/%y %H:%M %p')}"
  end
end

app/models/user.rb
class User < ApplicationRecord

  # CONSTANTS
  FIRST_NAME = %w(Objects Ruler Apparel Warm Cerium Every Jeans Spend Gogs Rounding Tophat Objectives Protective Box Funding Wizzed Trojan Prawns Quails Smile Lidar Mission Wavelength Dreary Glistering Apus Fizzy Sandbox Pestle Crookes Moaning Windows Barbarous Nosy Humbing Hopes Bummage Speaker Damned Hear Modest Presidents Passive Shrawns Jog Moustache Tale Weary Fags Divergent)
  LAST_NAME  = %w(Grumpy Bike Pedagogy Hopper Sname Clast Rat Puffs Tony Network Salt Frightened Mammal Reclusive Castration Cauliflower Flared Wedge Honky Southern Pimento Tekton Geiger Vomiting Flap Bubbly Kidneyed Peeler Sarrott Ascii Picket Surly Invention Catalysts Milky Uranium Shamb Tutors Mangled Listless Welcome Template Bunsen Gneeth Prepend Sheriff Realtor Fallen Fishy Karst)

  #ASSOCIATIONS
  has_many :matrices

  # CALLBACK
  before_create :set_default_values

  private

  def set_default_values
    self.name = [FIRST_NAME.sample, LAST_NAME.sample].join(' ')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :set_user

  private

  def set_user
    if session[:user_id]
      @current_user = User.where(id: session[:user_id]).first
    else
      # For testing with users from same ip, commenting IP check below.
      # @current_user = User.where(current_ip: request.remote_ip).first_or_create
      @current_user = User.create
      session[:user_id] = @current_user.id
    end
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  before_action :update_color_session, only: [:update_color]
  before_action :set_matrix, only: [:update_color]

  def index
    @matrices = Matrix.all.includes(:user)
  end

  def update_color
    if @matrix.update_color(session[:user_id], params[:color])
      ActionCable.server.broadcast "matrix_channel",
                                   { row: @matrix.row,
                                     column: @matrix.column,
                                     color: @matrix.color,
                                     title: @matrix.display_title }
      head :ok
    else
      head :unprocessable_entity
    end
  end

  private

  def update_color_session
    session[:color] = params[:color]
  end

  def set_matrix
    @matrix = Matrix.where(row: params[:row], column: params[:column]).first
    head :not_found unless @matrix
  end
end

app/controllers/leaderboard_controller.rb
class LeaderboardController < ApplicationController

  before_action :for_user, only: [:fav_colors]

  def index
    @top_users = Matrix.top_users
  end

  def fav_colors
    @fav_colors = @for_user.matrices.by_fav_colors
  end

  private

  def for_user
    @for_user = User.where(id: params[:user_id]).first
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper

  def td_content_tag matrix
    content_tag(:td, '', title: (matrix.display_title if matrix.user.present?),
                row: matrix.row, column: matrix.column,
                bgcolor: matrix.color, class: 'boxContainer')
  end

  def td_fav_color_tag fav_color
    content_tag(:td, fav_color.count, bgcolor: fav_color.color,
                class: 'favColorContainer')
  end

  def current_user_color
    session[:color] || random_color
  end

  def random_color
    "%06x" % (rand * 0xffffff)
  end
end

app/helpers/leaderboard_helper.rb
module LeaderboardHelper
end

app/views/dashboard/index.html.erb
<div class="alignCen">
  <input type="hidden" id="colorPicker" class="demo" value="<%= current_user_color %>"></br></br>

  <table>
    <% @matrices.in_groups_of(20).each do |rows| %>
      <tr>
        <% rows.each do |column| %>
          <%= td_content_tag(column) %>
        <% end %>
      </tr>
    <% end %>
  </table>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ColorPicker</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= render partial: 'shared/header' %>

    <div id="container">
      <%= yield %>
    </div>

    <%= render partial: 'shared/footer' %>

  </body>
</html>

app/views/leaderboard/_fav_colors.html.erb
<div class="alignCen">
  <table>
    <tr>
      <% @fav_colors.each do |fav_color| %>
        <%= td_fav_color_tag fav_color %>
      <% end %>
    </tr>
  </table>
</div>

app/views/leaderboard/fav_colors.js.erb
$(".favColorsForUser_<%= @for_user.id %>").html("<%= j(render(partial: 'fav_colors')) %>");

app/views/leaderboard/index.html.erb
<div class="alignCen">

  <h2>Top Users</h2>
  <div class="topUsersList">
    <% if @top_users.present? %>
      <% @top_users.each_with_index do |top_user, index| %>
        <%= index+1 %>.
        <b><%= top_user.user.name %></b> placed <span class="highlight"><%= top_user.distinct_color_count %></span> colors totaly.
        <%= link_to 'Fav Colors', fav_colors_path(user_id: top_user.user_id), remote: true %>
        <div class="favColorsForUser_<%= top_user.user_id %>"></div></br>
      <% end %>
    <% else %>
      Yet to get colorful.
    <% end %>
  </div>


</div>

app/views/shared/_footer.html.erb
<footer id="footer">
  <div class="clear"></div>
</footer>

app/views/shared/_header.html.erb
<header id="header">
  <div class="alignRight">
    <span class="margin20">Welcome: <span class="userName"><%= @current_user.name.camelcase %></span></span>
    <span class="margin20"><%= link_to 'Dashboard', root_path %></span>
    <span><%= link_to 'LeaderBoard', leaderboard_index_path %></span>
  </div>
</header>